import type { Metadata } from "next";
import "./globals.css";
import { Mona_Sans } from "next/font/google";
import Navigation from "./components/Navigation";

const monaSans = Mona_Sans({
  subsets: ["latin"],
  variable: "--font-mona-sans",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased ${monaSans.className}`}>
        <Navigation />
        <div className="max-w-6xl mx-auto px-4">{children}</div>
      </body>
    </html>
  );
}
