// Centralized constants for the Gitgenix app

// Default contribution values
export const DEFAULT_MIN_CONTRIBUTIONS = 10;
export const DEFAULT_MAX_CONTRIBUTIONS = 40;

export const weekLabels = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];

export const monthNames = [
  "Jan",
  "Feb",
  "Mar",
  "Apr",
  "May",
  "Jun",
  "Jul",
  "Aug",
  "Sep",
  "Oct",
  "Nov",
  "Dec",
];

export const creativeCommitMessages = [
  "Keep pushing forward! 🚀",
  "One step closer to greatness.",
  "Code, commit, conquer!",
  "Making history, one commit at a time.",
  "Refactoring reality.",
  "Dream big, code bigger.",
  "Turning coffee into code.",
  "Fun fact: This commit is awesome!",
  "Motivation: You got this!",
  "Another brick in the wall.",
  "Fun fact: Honey never spoils.",
  "Motivation: Progress, not perfection.",
  "Fun fact: Octopuses have three hearts.",
  "Motivation: Every commit counts!",
  "Fun fact: Bananas are berries!",
  "Motivation: Stay curious, keep coding.",
  "Fun fact: The Eiffel Tower can be 15 cm taller during hot days.",
  "Motivation: Small steps, big impact.",
  "Fun fact: A group of flamingos is called a flamboyance.",
  "Motivation: Code like nobody's watching!",
  "Building something amazing.",
  "Pixel by pixel, commit by commit.",
  "Creating digital art with code.",
  "Another day, another commit.",
  "Fun fact: Sharks existed before trees!",
  "Motivation: Embrace the process.",
  "Fun fact: A day on Venus is longer than its year.",
  "Crafting the future with commits.",
  "Fun fact: Wombat poop is cube-shaped!",
  "Motivation: Consistency beats perfection.",
  "Fun fact: There are more trees on Earth than stars in the galaxy.",
  "Building bridges with code.",
  "Fun fact: Bubble wrap was originally invented as wallpaper.",
  "Motivation: Every expert was once a beginner.",
  "Fun fact: A group of pugs is called a grumble.",
  "Painting the contribution graph.",
  "Fun fact: Banging your head against a wall burns 150 calories an hour.",
  "Motivation: Code is poetry in motion.",
  "Fun fact: Dolphins have names for each other.",
  "Creating patterns in the matrix.",
  "Fun fact: A shrimp's heart is in its head.",
  "Motivation: Innovation starts with iteration.",
  "Fun fact: It rains diamonds on Saturn and Jupiter.",
  "Weaving stories through commits.",
  "Fun fact: A group of owls is called a parliament.",
  "Motivation: Progress over perfection.",
  "Fun fact: Cleopatra lived closer to the moon landing than the pyramids being built.",
  "Sculpting code into art.",
  "Fun fact: A crocodile cannot stick its tongue out.",
  "Motivation: Every commit is a step forward."
];
