export const taglines = [
  "**Where Your Code Blooms** Over Time",
  "**Visualize Your Developer Journey**",
  "The **Landscape of Your Contributions**",
  "A **Garden of Code**, Year After Year",
  "**Trace the Flow** of Your Commits",
  "Your **Coding Story**, Beautifully Told",
  "**Mapping Growth**, One Commit at a Time",
  "The **Art of Contribution**, Perfected",
  "**Unfold Your Multi-Year Code Legacy**",
  "A **Timeless Canvas** of Development",
  "Every **Commit Counts**, Every Day Matters",
  "See Your **Progress in Full Spectrum**",
  "Where **Time Meets Creativity**",
  "Commit History in **Living Color**",
  "Your Code’s **Footprint Through the Years**",
  "**Tracking Growth** with Elegance and Precision",
  "Beyond Streaks: A **Visual Story of You**",
  "Watch Your **Code Garden Flourish**",
  "**Time-Arcs** of Innovation and Passion",
  "The **Pulse of Your Development Life**",
  "Bringing Your **Contribution Story to Life**",
  "A **Yearly Symphony** of Commits",
  "**Code, Time, and Beauty** Intertwined",
  "**Visualize Your Legacy**, One Pixel at a Time",
  "The **Rhythm of Your Developer Journey**",
  "From **Streaks to Stories**",
  "Where Your Code **Finds Its Reflection**",
  "A **New View** of Your Contribution History",
  "**Unlock the Patterns** in Your Coding Life",
  "Your **Dev Timeline**, Reimagined",
  "See the **Bigger Picture** of Your Work",
  "The **Pulse Grid** of Your Programming Life",
  "Every Day, **A Step Forward**",
  "**Capture the Essence** of Your Code Journey",
  "A **Visual Diary** of Your Developer Path"
];
